data <- read.csv("household_power_consumption.txt", sep=";", stringsAsFactors = FALSE)
neededData <- subset(data, Date=="1/2/2007" | Date=="2/2/2007")
GAP <- as.numeric(neededData$Global_active_power)
sm1 <- as.numeric(neededData$Sub_metering_1)
sm2 <- as.numeric(neededData$Sub_metering_2)
sm3 <- as.numeric(neededData$Sub_metering_3)
dateTime <- strptime(paste(neededData$Date, neededData$Time), "%d/%m/%Y %H:%M:%S")
png(filename = "plot4.png", width = 480, height = 480, units = "px")
par(mfrow=c(2,2))
plot(dateTime, GAP, type="n", ylab="Global Active Power", xlab="")
lines(dateTime, GAP)
voltage <- as.numeric(neededData$Voltage)
plot(dateTime, voltage, type="n", ylab="Voltage", xlab="datetime")
lines(dateTime, voltage)
plot(dateTime, sm1, type="n", xlab="", ylab="Energy sub metering")
lines(dateTime, sm1)
lines(dateTime, sm2, col="red")
lines(dateTime, sm3, col="blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=c(1,1,1), col=c("black", "red", "blue"), lwd =c(2.5,2.5,2.5), bty = "n")
GRP <- as.numeric(neededData$Global_reactive_power)
plot(dateTime, GRP, type="n", ylab="Global_reactive_power", xlab="datetime")
lines(dateTime, GRP)
dev.off()